### ISSUE TITLE
About IEEE-CLS-Fraud dataset

### ISSUE THREAD

**Issue by QX-N** [wey-gu/NebulaGraph-Fraud-Detection-GNN#4]
Hello, how can I use the IEEE-cls-fraud dataset to implement this code? What parts of the code need to be modified?

**Comment by wey-gu** [comment]
Hi @QX-N ,

I was on vacation last week, sorry for the late response.

You could define the edge/relationship from the dataset, preprocess the properties that's needed, etl it to NebulaGraph.

Then rewrite the yaml file that maps the graph data fro NebulaGraph to dgl.

**Comment by QX-N** [comment]
Thanks for your reply， but now I met some problems running this repo in my win11 system, I don't know what doc I can refer to run this program with windows.

**Comment by wey-gu** [comment]
I recommend running things in linux as much as possible, you could put everything in an Ubuntu WSL2 on Win11 :)

Things are always harder in Windows as I know, thus I aways avoid doing so.

**Comment by QX-N** [comment]
Thanks for your reply!
