### ISSUE TITLE
Could you provide the trained model？

### ISSUE THREAD

**Issue by QX-N** [wey-gu/NebulaGraph-Fraud-Detection-GNN#7]
Hello， I only want to run the  Real Time Fraud Monitor Dashboards. Could you provide the trained model?
I would appreciate it very much if you can provide it.

**Comment by wey-gu** [comment]
~~Oh, sorry, I didn't persist the model, but it's actually not slow to train it even in CPU as I recall.~~

It's in the release!

https://github.com/wey-gu/NebulaGraph-Fraud-Detection-GNN/releases/tag/v0.0.1

**Comment by QX-N** [comment]
Thanks for your reply. I am stuck in this procedure. It has cost me 20 minutes to loader this graph. I don't know why.
![image](https://github.com/wey-gu/NebulaGraph-Fraud-Detection-GNN/assets/108463784/e773eb02-5d90-42c9-92d4-908252e0219b)

**Comment by QX-N** [comment]
It's grateful!!!

**Comment by wey-gu** [comment]
This should be as expected, now the nebula-dgl's data scanning is relatively slow(need some optimization), please wait for some time :-D

**Comment by QX-N** [comment]
I use the same command to create jovyan docker， what's the root password？ I tried some like “nebulagraph” “secret” and this doesn't work.

**Comment by wey-gu** [comment]
> 

for notebook or for container? for container there is no password, you could use -u root to enter container as root user. for notebook, try nebula, or you could override it with container env var as I recall

**Comment by QX-N** [comment]
![image](https://github.com/wey-gu/NebulaGraph-Fraud-Detection-GNN/assets/108463784/885204ad-006e-4374-837d-8b018ec0d3d2)
![image](https://github.com/wey-gu/NebulaGraph-Fraud-Detection-GNN/assets/108463784/99e48864-469d-4bb7-a2fa-e7bbdb8ad2e0)
How to display this data result on the frontend interface?

**Comment by wey-gu** [comment]
the backend should push this to the browser with websocket, ensure everything was configured properly?

**Comment by QX-N** [comment]
I'm confident that I've followed all the steps in your README. Below is my backend configuration file, but currently, the frontend interface cannot display my data. Is there any good solution for this?



user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  4096;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

    # include /etc/nginx/conf.d/*.conf;

    server {
        listen 15000;
        server_name 10.184.17.30;

        location / {
            add_header 'Access-Control-Allow-Origin' '*' always;
            proxy_pass http://host.docker.internal:5000; # backend
            proxy_redirect off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # reverse proxy for Socket.IO connections
        location /socket.io {
            proxy_pass http://host.docker.internal:5000/socket.io; # backend
            proxy_http_version 1.1;
            proxy_redirect off;
            proxy_buffering off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
    server {
        listen 8080;
        server_name 10.184.17.30;
        root /data ;
        gzip on;
        gzip_vary on;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_min_length 1k;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+css text/javascript;

        location / {
            # add_header 'Access-Control-Allow-Origin' '*' always;
            root /data ;
            try_files $uri $uri/ @rewrites;
        }

        location @rewrites {
            rewrite ^(.+)$ /index.html last;
        }

        location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
            # Some basic cache-control for static files to be sent to the browser
            expires max;
            add_header Pragma public;
            add_header Cache-Control "public, must-revalidate, proxy-revalidate";
        }
    }
}

**Comment by QX-N** [comment]
my_ip is 10.184.17.30

**Comment by wey-gu** [comment]
yes, in my code, the my_ip is hardcoded, thus we have to `sed` to replace them, could you double check that, please?
```
# ADD MY_IP into CORS & Frontend file, nginx.conf
sed -i "s/nebula-demo.siwei.io/$MY_IP/g" fraudd_backend/fraudd/__init__.py
sed -i "s/nebula-demo.siwei.io/$MY_IP/g" fraudd_frontend/src/components/Table.vue
sed -i "s/nebula-demo.siwei.io/$MY_IP/g" nginx.conf
```

**Comment by QX-N** [comment]
I have already performed the verification, and the command executed successfully.

**Comment by wey-gu** [comment]
could you check console from browser to see if there are any errors?

**Comment by wey-gu** [comment]
And ensure you did the replacement before pip installation

**Comment by QX-N** [comment]
Thanks for your reply！
