### ISSUE TITLE
Set an example for "is_fraud = True"。

### ISSUE THREAD

**Issue by QX-N** [wey-gu/NebulaGraph-Fraud-Detection-GNN#8]
I tried many examples, and the result is always "is_fraud = False." Is there an example where "is_fraud = True" exists?

**Comment by QX-N** [comment]
![image](https://github.com/wey-gu/NebulaGraph-Fraud-Detection-GNN/assets/108463784/ec72c150-3988-4943-ae73-38daa3f7e9a1)

**Comment by wey-gu** [comment]
The nature of is_fraud distribution is sparse, I guess you had found some that's positively fraud.
